services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=eventhub-db'
      - 'POSTGRES_USER=tsu'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"