name: TSU EventHub API CI/CD

on:
  push:
    branches: [main]

env:
  JAVA_VERSION: '21'
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/tsu-eventhub-api
  DEPLOY_USERNAME: 'deployuser'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: 📦 Build with Maven
        run: mvn clean package -DskipTests

      - name: 📁 Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target-artifacts
          path: target/*.jar

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.run_number }}

      - name: 🚀 Deploy to Server (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ env.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "📦 Save previous container as a backup..."
            docker tag tsu-eventhub-api tsu-eventhub-api-backup || true

            echo "📥 Pull last image..."
            docker pull ${{ env.DOCKER_IMAGE }}:latest

            echo "🛑 Stopping and deleting current container..."
            docker stop tsu-eventhub-api || true
            docker rm tsu-eventhub-api || true

            echo "🚀 Launching a new container with secrets from server environment..."
            docker run -d --name tsu-eventhub-api -p 8080:8080 --env-file /home/${{ env.DEPLOY_USERNAME }}/tsu-eventhub.env --network tsu-eventhub_net ${{ env.DOCKER_IMAGE }}:latest

      - name: 🛠 Rollback
        if: failure()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ env.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "⚠️ Deployment error. Rollback to previous container..."
            docker stop tsu-eventhub-api || true
            docker rm tsu-eventhub-api || true
            docker run -d --name tsu-eventhub-api -p 8080:8080 --env-file /home/${{ env.DEPLOY_USERNAME }}/tsu-eventhub.env --network tsu-eventhub_net tsu-eventhub-api-backup